[package]
name = "starcrawl"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
async-trait = "0.1.68"
num-traits = "0.2.15"
s2rs = { version = "0.5.15", features = ["html"] }
s2rs-derive = "0.1.2"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
