[package]
name = "starbucket"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
s2rs = "0.7.15"
s2rs-derive = "0.1.2"
starcrawl = { version = "0.1.0", path = "../starcrawl" }

[dev-dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }